blueprint:
  name: Smart Button with Event Entities
  description: >-
    Configure Smart Button with Event Entities (experimental).
    Supports SINGLE, DOUBLE and HOLD without losing first press.
  domain: automation
  author: Alex Soto Aguilera
  source_url: https://github.com/alexsotoaguilera/homeassistant/tree/main/blueprints/automation/alexsotoaguilera/smartbutton-event-entities.yaml
  homeassistant:
    min_version: 2022.4.0

input:
  event_entity:
    name: Button Event Entity
    description: >-
      Select `event.button_name_action` (enable experimental_event_entities in Z2M).
      Example: event.living_room_ts0041_action
    selector:
      entity:
        domain: event
        multiple: false
  actions_single:
    name: Single Tap Actions
    description: Actions to activate with SINGLE tap
    selector:
      action: {}
  actions_double:
    name: Double Tap Actions
    description: Actions to activate with Double tap
    selector:
      action: {}
  actions_hold:
    name: Hold Tap Actions
    description: Actions to activate with Hold tap
    selector:
      action: {}

triggers:
  - trigger: state
    entity_id: !input event_entity
    id: single_double_hold

action:
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ trigger.to_state.attributes.event_type == 'single' }}"
        sequence: !input "actions_single"
      - conditions:
          - condition: template
            value_template: "{{ trigger.to_state.attributes.event_type == 'double' }}"
        sequence: !input "actions_double"
      - conditions:
          - condition: template
            value_template: "{{ trigger.to_state.attributes.event_type == 'hold' }}"
        sequence: !input "actions_hold"

mode: single
